//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using Cuahanghoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khachhang()
        {
            this.Phieuxuatchitiet = new HashSet<Phieuxuatchitiet>();
        }

        private int _Idkhachhang;
        public int Idkhachhang { get => _Idkhachhang; set { _Idkhachhang = value; OnPropertyChanged(); } }

        private string _Tenkhachhang;
        public string Tenkhachhang { get => _Tenkhachhang; set { _Tenkhachhang = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _Ngaysinh;
        public Nullable<System.DateTime> Ngaysinh { get => _Ngaysinh; set { _Ngaysinh = value; OnPropertyChanged(); } }

        private string _Diachi;
        public string Diachi { get => _Diachi; set { _Diachi = value; OnPropertyChanged(); } }

        private string _Dienthoai;
        public string Dienthoai { get => _Dienthoai; set { _Dienthoai = value; OnPropertyChanged(); } }

        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieuxuatchitiet> Phieuxuatchitiet { get; set; }
    }
}
