//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuahanghoaEntities1 : DbContext
    {
        public CuahanghoaEntities1()
            : base("name=CuahanghoaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Khachhang> Khachhang { get; set; }
        public virtual DbSet<Nguoidung> Nguoidung { get; set; }
        public virtual DbSet<Nhacungcap> Nhacungcap { get; set; }
        public virtual DbSet<Phanquyennguoidung> Phanquyennguoidung { get; set; }
        public virtual DbSet<Phieunhap> Phieunhap { get; set; }
        public virtual DbSet<Phieunhapchitiet> Phieunhapchitiet { get; set; }
        public virtual DbSet<Phieuxuat> Phieuxuat { get; set; }
        public virtual DbSet<Phieuxuatchitiet> Phieuxuatchitiet { get; set; }
        public virtual DbSet<Sanpham> Sanpham { get; set; }
    }
}
