//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using Cuahanghoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Nguoidung: BaseViewModel
    {
        private int _Idnguoidung;
        public int Idnguoidung { get=> _Idnguoidung; set { _Idnguoidung = value;OnPropertyChanged(); } }

        private string _Tenhienthi;
        public string Tenhienthi { get => _Tenhienthi; set { _Tenhienthi = value;OnPropertyChanged(); } }

        private string _Tendangnhap;
        public string Tendangnhap { get => _Tendangnhap; set { _Tendangnhap = value;OnPropertyChanged(); } }

        private string _Matkhau;
        public string Matkhau { get=>_Matkhau; set { _Matkhau = value;OnPropertyChanged(); } }

        private int _Idquyen;
        public int Idquyen { get => _Idquyen; set { _Idquyen = value;OnPropertyChanged(); } }


        private Phanquyennguoidung _Phanquyennguoidung;
        public virtual Phanquyennguoidung Phanquyennguoidung { get=> _Phanquyennguoidung; set { _Phanquyennguoidung = value;OnPropertyChanged(); } }
    }
}
