//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using Cuahanghoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Phieuxuatchitiet: BaseViewModel
    {
        private string _Idphieuxuatchitiet;
        public string Idphieuxuatchitiet { get => _Idphieuxuatchitiet; set { _Idphieuxuatchitiet = value; OnPropertyChanged(); } }

        private string _Idphieuxuat;
        public string Idphieuxuat { get => _Idphieuxuat; set { _Idphieuxuat = value; OnPropertyChanged(); } }

        private string _Idsanpham;
        public string Idsanpham { get => _Idsanpham; set { _Idsanpham = value; OnPropertyChanged(); } }

        private string _Idphieunhapchitiet;
        public string Idphieunhapchitiet { get => _Idphieunhapchitiet; set { _Idphieunhapchitiet = value; OnPropertyChanged(); } }

        private int _Idkhachhang;
        public int Idkhachhang { get => _Idkhachhang; set { _Idkhachhang = value; OnPropertyChanged(); } }

        private Nullable<int> _Soluong;
        public Nullable<int> Soluong { get => _Soluong; set { _Soluong = value; OnPropertyChanged(); } }

        private Nullable<double> _Tongtien;
        public Nullable<double> Tongtien { get => _Tongtien; set { _Tongtien = value; OnPropertyChanged(); } }


        private Khachhang _Khachhang;
        public virtual Khachhang Khachhang { get => _Khachhang; set { _Khachhang = value; OnPropertyChanged(); } }

        private Phieunhapchitiet _Phieunhapchitiet;
        public virtual Phieunhapchitiet Phieunhapchitiet { get => _Phieunhapchitiet; set { _Phieunhapchitiet = value; OnPropertyChanged(); } }

        private Phieuxuat _Phieuxuat;
        public virtual Phieuxuat Phieuxuat { get => _Phieuxuat; set { _Phieuxuat = value; OnPropertyChanged(); } }

        private Sanpham _Sanpham;
        public virtual Sanpham Sanpham { get => _Sanpham; set { _Sanpham = value; OnPropertyChanged(); } }

    }
}
