//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using Cuahanghoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Phieunhapchitiet: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieunhapchitiet()
        {
            this.Phieuxuatchitiet = new HashSet<Phieuxuatchitiet>();
        }

        private string _Idphieunhapchitiet;
        public string Idphieunhapchitiet { get => _Idphieunhapchitiet; set { _Idphieunhapchitiet = value; OnPropertyChanged(); } }

        private string _Idphieunhap;
        public string Idphieunhap { get => _Idphieunhap; set { _Idphieunhap = value; OnPropertyChanged(); } }

        private string _Idsanpham;
        public string Idsanpham { get => _Idsanpham; set { _Idsanpham = value; OnPropertyChanged(); } }

        private Nullable<int> _Soluong;
        public Nullable<int> Soluong { get => _Soluong; set { _Soluong = value; OnPropertyChanged(); } }

        private Nullable<double> _Gianhap;
        public Nullable<double> Gianhap { get => _Gianhap; set { _Gianhap = value; OnPropertyChanged(); } }

        private Nullable<double> _Giaxuat;
        public Nullable<double> Giaxuat { get => _Giaxuat; set { _Giaxuat = value; OnPropertyChanged(); } }

        private Phieunhap _Phieunhap;
        public virtual Phieunhap Phieunhap { get => _Phieunhap; set { _Phieunhap = value; OnPropertyChanged(); } }

        private Sanpham _Sanpham;
        public virtual Sanpham Sanpham { get => _Sanpham; set { _Sanpham = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieuxuatchitiet> Phieuxuatchitiet { get; set; }
    }
}
