//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuahanghoa.Model
{
    using Cuahanghoa.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Phieunhapchitiet = new HashSet<Phieunhapchitiet>();
            this.Phieuxuatchitiet = new HashSet<Phieuxuatchitiet>();
        }

        private string _Idsanpham;
        public string Idsanpham { get => _Idsanpham; set { _Idsanpham = value; OnPropertyChanged(); } }

        private string _Tensanpham;
        public string Tensanpham { get => _Tensanpham; set { _Tensanpham = value; OnPropertyChanged(); } }

        private int _Idnhacungcap;
        public int Idnhacungcap { get => _Idnhacungcap; set { _Idnhacungcap = value; OnPropertyChanged(); } }

        private Nhacungcap _Nhacungcap;
        public virtual Nhacungcap Nhacungcap { get => _Nhacungcap; set { _Nhacungcap = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieunhapchitiet> Phieunhapchitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieuxuatchitiet> Phieuxuatchitiet { get; set; }
    }
}
